language: ruby
cache: bundler
dist: xenial

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --jobs 7 --without docs debug
script:
  - bundle exec rake style
  - bundle exec rake spec
