version: "master-{build}"

os: Visual Studio 2017
platform:
  - x64

cache:
  - vendor/bundle
environment:
  matrix:
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "24-x64"
    - ruby_version: "24"
    - ruby_version: "23-x64"
    - ruby_version: "23"

clone_folder: c:\projects\win32-certstore
clone_depth: 1

skip_commits:
  # version bumps by Expeditor happen as a separate commit after the merge, we can skip
  message: /Bump version to [0-9.]+ by Chef Expeditor/
  # if ONLY the files listed below are changed in a commit, skip
  files:
    - MAINTAINERS.md
    - MAINTAINERS.toml
    - CHANGELOG.md
    - RELEASE_NOTES.md

skip_tags: true
branches:
  only:
    - master

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ps: $env:OMNIBUS_RUBYGEMS=$(findstr rubygems omnibus_overrides.rb | %{ $_.split(" ")[3] })
  - echo %OMNIBUS_RUBYGEMS%
  - ps: $env:OMNIBUS_BUNDLER=$(findstr bundler omnibus_overrides.rb | %{ $_.split(" ")[3] })
  - echo %OMNIBUS_BUNDLER%
  - ruby --version
  - gem --version
  - gem update --system %OMNIBUS_RUBYGEMS% || gem update --system %OMNIBUS_RUBYGEMS% || gem update --system %OMNIBUS_RUBYGEMS%
  - gem --version
  - bundler --version
  - SET BUNDLE_WITHOUT=server:docgen:maintenance:pry:travis:integration:ci
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - bundle env

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake style
  - bundle exec rake spec
